import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  useUser,
  UserButton,
} from "@clerk/nextjs";
 

import { api } from "~/utils/api";

const Home: NextPage = () => {

    const user = useUser();
    const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Mikes T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

          <div>
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Mikes <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          </div>

            <div>
                        <SignedIn>
                            {/* Mount the UserButton component */}
                            <UserButton />
                          </SignedIn>
                          <SignedOut>
                            {/* Signed out users get sign in button */}
                            <SignInButton />
                          </SignedOut>
            </div>
                    <div>
                    {data?.map((post) => (
                      <div key={post.id}>{post.content}</div>
                    ))}
                    </div>
            
      </main>
    </>
  );
};

export default Home;