import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  useUser,
  UserButton,
} from "@clerk/nextjs";
 

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="mx-auto flex gap-5 mt-8 max-w-7xl items-center justify-center p-6 lg:px-8">
      <img src={user.profileImageUrl} alt="User" className="w-24 h-24 rounded-full" />
      <input placeholder="type something" className="p-2 focus:outline-1 text-[#7E8490] focus:outline-blue-500 font-bold border-[0.1px] resize-none h-[96px] border-[#9EA5B1] rounded-md w-[60vw]" />
    </div>
  );
};


const Home: NextPage = () => {

    const user = useUser();
    const { data, isLoading } = api.posts.getAll.useQuery();

    if (isLoading) return <div>Loading...</div>;
    if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Mikes T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-white">
      <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
        <div className="flex lg:flex-1"><a href="#" className="-m-1.5 p-1.5">
            <span className="text-base font-semibold leading-7 text-gray-900">Your Company</span>
          </a></div>
          <div className="py-6">
              <SignedIn>
                {/* Mount the UserButton component */}
                <UserButton />
              </SignedIn>
              <SignedOut>
                <SignInButton>
                  <button className="inline-flex justify-center rounded-lg text-sm font-semibold py-2.5 px-4 bg-slate-900 text-white hover:bg-slate-700 -my-2.5 ml-8">Sign in <span aria-hidden="true">→</span></button>
                </SignInButton>
              </SignedOut>
          </div>
      </nav>
      </header>
      <main className="flex min-h-screen max-w-7xl flex-col items-center justify-flexstart bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="mb-8">
          {[ user.isSignedIn && <CreatePostWizard /> ]}
        </div>
        <div className="mb-8">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Mikes <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
        </div>
        <div className="flex flex-col">
          {[...data, ...data]?.map((post) => (
            <div key={post.id} className="p-8 border-b-2 border-slate-400">{post.content}</div>
          ))}
        </div>
            
      </main>
    </>
  );
};

export default Home;